### ISSUE TITLE
Update logo on the pages

### ISSUE THREAD

**Issue by paragasu** [phisoft/prestigeortho-web#27]
<img width="528" alt="Screenshot 2020-09-12 at 11 04 11 AM" src="https://user-images.githubusercontent.com/27353/92985713-c3556e00-f4e7-11ea-8658-f872a307c994.png">

**Comment by izahshahirah** [comment]
I already update the logo last week.

<img width="1751" alt="Screenshot 2020-09-14 at 8 44 20 AM" src="https://user-images.githubusercontent.com/60636305/93034440-9f6f6500-f66c-11ea-9dee-0cbcec30a719.png">

**Comment by paragasu** [comment]
Mau semua pages tu @izahshahirah
