### ISSUE TITLE
Update team & partners

### ISSUE THREAD

**Issue by paragasu** [phisoft/prestigeortho-web#4]
[22:41, 03/08/2020] Kenneth: the our team part
[22:41, 03/08/2020] Kenneth: add the same
[22:42, 03/08/2020] Kenneth: with 
Wong & Sim Dental Surgery (Pulau Tikus) 
Wong & Sim Dental Surgery (Summerton) 
Klinik Pakar Periodontik & Pergigian Freeda Woon

![image](https://user-images.githubusercontent.com/27353/89198824-5691ae80-d5e0-11ea-996f-54805fb5228d.png)

**Comment by qoszira15** [comment]
Done.
