### ISSUE TITLE
Delete map & info

### ISSUE THREAD

**Issue by paragasu** [phisoft/prestigeortho-web#5]
![image](https://user-images.githubusercontent.com/27353/89198911-7032f600-d5e0-11ea-9101-d295c43d76fb.png)

[22:43, 03/08/2020] Kenneth: delete this
[22:43, 03/08/2020] Kenneth: dont need to show dr chay firts

![image](https://user-images.githubusercontent.com/27353/89199061-a1132b00-d5e0-11ea-9358-333f4f4d5c92.png)
delete

**Comment by qoszira15** [comment]
Done.
